{ pkgs, ... }: let
  user = "george";
in {
  system.stateVersion = 4;

  nixpkgs.config.allowUnfree = true;

  environment = {
    shells = with pkgs; [ bash zsh ];
    loginShell = pkgs.zsh;
    pathsToLink = [
      "/Applications"
      "/share/zsh"
    ];
    systemPackages = with pkgs; [
      coreutils
    ];
  };

  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = true;
      cleanup = "zap";
      upgrade = true;
    };
    casks = [
      "1password"
      "1password-cli"
      "slack"
      "tailscale"
      "rectangle"
    ];
    masApps = {
      "1Password for Safari" = 1569813296;
      "Fantastical" = 975937182;
      "Omnifocus 3" = 1346203938; 
    };
  };

  fonts.fontDir.enable = true;
  fonts.fonts = with pkgs; [
     (nerdfonts.override { fonts = [ "RobotoMono" ]; })
   ];

  nix = {
    settings = {
      bash-prompt-prefix = "(nix:$name)\040";
      build-users-group = "nixbld";
      experimental-features = [
        "auto-allocate-uids"
        "flakes"
        "nix-command"
      ];
      trusted-users = [ "@admin" "${user}" ];
    };
    extraOptions = ''
      # Generated by https://github.com/DeterminateSystems/nix-installer, version 0.11.0.
      extra-nix-path = nixpkgs=flake:nixpkgs
    '';
  };

  programs.zsh.enable = true;

  services.nix-daemon.enable = true;

  users.users.${user} = {
    home = "/Users/${user}";
    shell = pkgs.zsh;
  };
}